import { PresetRequirement } from '../types';

export const BUILT_IN_PRESETS: PresetRequirement[] = [
  // --- PASSPORT PHOTOS ---
  {
    id: 'us-passport',
    name: 'US Passport / Visa Photo',
    category: 'passport',
    countryOrOrg: 'United States',
    description: 'Official 2 x 2 inch biometric passport & visa photo.',
    width: 2,
    height: 2,
    unit: 'inch',
    dpi: 300,
    format: 'jpeg',
    maxKb: 240,
    minKb: 10,
    bgColor: '#ffffff',
    bgType: 'white',
    faceGuideRatio: {
      headMinPercent: 50,
      headMaxPercent: 69,
      eyeLevelPercent: 62,
    },
  },
  {
    id: 'uk-eu-passport',
    name: 'UK / EU / Schengen Passport',
    category: 'passport',
    countryOrOrg: 'UK & European Union',
    description: 'Standard 35 x 45 mm biometric passport photo.',
    width: 35,
    height: 45,
    unit: 'mm',
    dpi: 300,
    format: 'jpeg',
    maxKb: 200,
    minKb: 10,
    bgColor: '#f1f5f9',
    bgType: 'light',
    faceGuideRatio: {
      headMinPercent: 65,
      headMaxPercent: 78,
      eyeLevelPercent: 58,
    },
  },
  {
    id: 'india-passport',
    name: 'Indian Passport (35 x 45 mm)',
    category: 'passport',
    countryOrOrg: 'India',
    description: 'Standard Indian Passport Seva Kendra photograph.',
    width: 35,
    height: 45,
    unit: 'mm',
    dpi: 300,
    format: 'jpeg',
    maxKb: 100,
    minKb: 20,
    bgColor: '#ffffff',
    bgType: 'white',
    faceGuideRatio: {
      headMinPercent: 60,
      headMaxPercent: 75,
      eyeLevelPercent: 60,
    },
  },
  {
    id: 'india-passport-square',
    name: 'Indian Passport / Visa Square (51 x 51 mm)',
    category: 'passport',
    countryOrOrg: 'India / OCI',
    description: 'Square 51 x 51 mm (2 x 2 inch) photo for OCI / Visa.',
    width: 51,
    height: 51,
    unit: 'mm',
    dpi: 300,
    format: 'jpeg',
    maxKb: 200,
    minKb: 20,
    bgColor: '#ffffff',
    bgType: 'white',
  },
  {
    id: 'canada-passport',
    name: 'Canada Passport Photo',
    category: 'passport',
    countryOrOrg: 'Canada',
    description: 'Official 50 x 70 mm Canadian passport photo.',
    width: 50,
    height: 70,
    unit: 'mm',
    dpi: 300,
    format: 'jpeg',
    maxKb: 300,
    bgColor: '#ffffff',
    bgType: 'white',
  },
  {
    id: 'australia-passport',
    name: 'Australia Passport Photo',
    category: 'passport',
    countryOrOrg: 'Australia',
    description: 'Official 35 x 45 mm Australian passport format.',
    width: 35,
    height: 45,
    unit: 'mm',
    dpi: 300,
    format: 'jpeg',
    maxKb: 200,
    bgColor: '#ffffff',
    bgType: 'white',
  },

  // --- EXAMS & RECRUITMENT ---
  {
    id: 'upsc-photo',
    name: 'UPSC Civil Services Photo',
    category: 'exam',
    countryOrOrg: 'UPSC',
    description: 'Direct 350 x 350 px photograph under 300 KB.',
    width: 350,
    height: 350,
    unit: 'px',
    dpi: 150,
    format: 'jpeg',
    maxKb: 300,
    minKb: 20,
    bgColor: '#ffffff',
  },
  {
    id: 'upsc-signature',
    name: 'UPSC Civil Services Signature',
    category: 'exam',
    countryOrOrg: 'UPSC',
    description: 'Direct 350 x 350 px signature under 300 KB.',
    width: 350,
    height: 350,
    unit: 'px',
    dpi: 150,
    format: 'jpeg',
    maxKb: 300,
    minKb: 20,
    bgColor: '#ffffff',
  },
  {
    id: 'ssc-photo',
    name: 'SSC Exam Photograph',
    category: 'exam',
    countryOrOrg: 'Staff Selection Commission',
    description: '3.5 x 4.5 cm (approx 100 x 120 px), strictly 20 - 50 KB.',
    width: 3.5,
    height: 4.5,
    unit: 'cm',
    dpi: 200,
    format: 'jpeg',
    maxKb: 50,
    minKb: 20,
    bgColor: '#ffffff',
  },
  {
    id: 'ssc-signature',
    name: 'SSC Exam Signature',
    category: 'exam',
    countryOrOrg: 'Staff Selection Commission',
    description: '4.0 x 2.0 cm signature, strictly 10 - 20 KB.',
    width: 4.0,
    height: 2.0,
    unit: 'cm',
    dpi: 200,
    format: 'jpeg',
    maxKb: 20,
    minKb: 10,
    bgColor: '#ffffff',
  },
  {
    id: 'ibps-photo',
    name: 'IBPS Bank PO / Clerk Photo',
    category: 'exam',
    countryOrOrg: 'IBPS Banking',
    description: '4.5 x 3.5 cm (200 x 230 px), strictly 20 - 50 KB.',
    width: 3.5,
    height: 4.5,
    unit: 'cm',
    dpi: 200,
    format: 'jpeg',
    maxKb: 50,
    minKb: 20,
    bgColor: '#ffffff',
  },
  {
    id: 'ibps-signature',
    name: 'IBPS Bank PO / Clerk Signature',
    category: 'exam',
    countryOrOrg: 'IBPS Banking',
    description: '140 x 60 px signature in black ink, strictly 10 - 20 KB.',
    width: 140,
    height: 60,
    unit: 'px',
    dpi: 96,
    format: 'jpeg',
    maxKb: 20,
    minKb: 10,
    bgColor: '#ffffff',
  },
  {
    id: 'ibps-thumb',
    name: 'IBPS Left Thumb Impression',
    category: 'exam',
    countryOrOrg: 'IBPS Banking',
    description: '3 x 3 cm (240 x 240 px) blue/black thumb ink, 20 - 50 KB.',
    width: 3.0,
    height: 3.0,
    unit: 'cm',
    dpi: 200,
    format: 'jpeg',
    maxKb: 50,
    minKb: 20,
    bgColor: '#ffffff',
  },
  {
    id: 'gate-photo',
    name: 'GATE Exam Photo',
    category: 'exam',
    countryOrOrg: 'IIT GATE',
    description: '3.5 x 4.5 cm (aspect ratio 0.77), 5 - 200 KB.',
    width: 3.5,
    height: 4.5,
    unit: 'cm',
    dpi: 300,
    format: 'jpeg',
    maxKb: 200,
    minKb: 5,
    bgColor: '#ffffff',
  },
  {
    id: 'gate-signature',
    name: 'GATE Exam Signature',
    category: 'exam',
    countryOrOrg: 'IIT GATE',
    description: '2.0 x 7.0 cm signature, 5 - 100 KB.',
    width: 7.0,
    height: 2.0,
    unit: 'cm',
    dpi: 300,
    format: 'jpeg',
    maxKb: 100,
    minKb: 5,
    bgColor: '#ffffff',
  },

  // --- GENERAL SIGNATURES & CARDS ---
  {
    id: 'general-signature-png',
    name: 'Official Digital Signature (Transparent PNG)',
    category: 'application',
    description: 'Crisp transparent signature ready to sign PDFs and letters.',
    width: 600,
    height: 240,
    unit: 'px',
    dpi: 300,
    format: 'png',
    maxKb: 100,
    bgColor: 'transparent',
  },
  {
    id: 'general-signature-jpg',
    name: 'Official Signature (White Background JPG)',
    category: 'application',
    description: 'Standard white background signature under 50 KB.',
    width: 600,
    height: 250,
    unit: 'px',
    dpi: 300,
    format: 'jpeg',
    maxKb: 50,
    bgColor: '#ffffff',
  },
  {
    id: 'general-thumb-impression',
    name: 'Biometric Thumb Impression',
    category: 'application',
    description: 'High-contrast dermal ridge thumb impression for applications.',
    width: 400,
    height: 400,
    unit: 'px',
    dpi: 300,
    format: 'jpeg',
    maxKb: 50,
    minKb: 10,
    bgColor: '#ffffff',
  },
  {
    id: 'photo-sign-combo',
    name: 'Photograph + Signature Combo Slip',
    category: 'application',
    description: 'Combined portrait and signature block for single-upload forms.',
    width: 3.5,
    height: 6.0,
    unit: 'cm',
    dpi: 300,
    format: 'jpeg',
    maxKb: 100,
    minKb: 20,
    bgColor: '#ffffff',
  },
  {
    id: 'driving-license-photo',
    name: 'Driving License / PAN Card Photo',
    category: 'application',
    description: 'Standard 2.5 x 3.5 cm or 3.5 x 4.5 cm ID photo under 50 KB.',
    width: 25,
    height: 35,
    unit: 'mm',
    dpi: 300,
    format: 'jpeg',
    maxKb: 50,
    bgColor: '#ffffff',
  },
  {
    id: 'linkedin-profile',
    name: 'LinkedIn / Professional Avatar',
    category: 'social',
    description: 'Square 800 x 800 px crisp headshot.',
    width: 800,
    height: 800,
    unit: 'px',
    dpi: 150,
    format: 'jpeg',
    maxKb: 500,
  },
];

const LOCAL_STORAGE_KEY = 'docuprep_custom_presets_v1';

export function getCustomPresets(): PresetRequirement[] {
  try {
    const raw = localStorage.getItem(LOCAL_STORAGE_KEY);
    return raw ? JSON.parse(raw) : [];
  } catch {
    return [];
  }
}

export function saveCustomPreset(preset: PresetRequirement): void {
  try {
    const existing = getCustomPresets().filter((p) => p.id !== preset.id);
    existing.push(preset);
    localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(existing));
  } catch (e) {
    console.error('Failed to save custom preset to localStorage', e);
  }
}

export function deleteCustomPreset(id: string): void {
  try {
    const existing = getCustomPresets().filter((p) => p.id !== id);
    localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(existing));
  } catch (e) {
    console.error('Failed to delete custom preset', e);
  }
}

export function getAllPresets(): PresetRequirement[] {
  return [...BUILT_IN_PRESETS, ...getCustomPresets()];
}
